services:
  calculation-server:
    image: lyazginad/calc:server
    ports:
      - "8080:8080"
    networks:
      - calculation-net
    restart: unless-stopped
    container_name: calculation-server
    labels:
      - "author=Daria Lyazgina"
      - "email=daria.lyazgina@gmail.com"
      - "maintainer=Daria Lyazgina"

networks:
  calculation-net:
    driver: bridge